version: '3.7'

services:
  app:
    image: ${PROJECT_NAMESPACE}/dev-${APP_NAME}
    build:
      target: develop
    volumes:
      - ../:/var/www/app:cached
    ports:
      - "${NODE_SERVER_PORT}:8080"
      - "${SUPERVISOR_HTTP_PORT}:9009"
